In [1]:
import pandas as pd

In [2]:
ls

 Volume in drive C has no label.
 Volume Serial Number is EA81-4F3B

 Directory of C:\Users\USER\Desktop\Artificial_Intelligence_Course\week3_homework\ Loan Prediction - Classification

08.08.2025  19:52    <DIR>          .
08.08.2025  19:29    <DIR>          ..
08.08.2025  19:29    <DIR>          .ipynb_checkpoints
08.08.2025  19:52            95.789 Loan Prediction - Classification.ipynb
06.08.2025  19:50        16.542.823 LoanPrediction.zip
06.08.2025  19:50           130.260 LoansTraining data dictionary.docx
06.08.2025  19:50        47.630.611 LoansTrainingSet.csv
               4 File(s)     64.399.483 bytes
               3 Dir(s)  127.337.517.056 bytes free


In [3]:
df = pd.read_csv('LoansTrainingSet.csv')

C:\Users\USER\AppData\Local\Temp\ipykernel_27992\3228652955.py:1: DtypeWarning: Columns (16) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv('LoansTrainingSet.csv')


In [4]:
df.head()

,Loan ID,Customer ID,Loan Status,Current Loan Amount,Term,Credit Score,Years in current job,Home Ownership,Annual Income,Purpose,Monthly Debt,Years of Credit History,Months since last delinquent,Number of Open Accounts,Number of Credit Problems,Current Credit Balance,Maximum Open Credit,Bankruptcies,Tax Liens
0,000025bb-5694-4cff-b17d-192b1a98ba44,5ebc8bb1-5eb9-4404-b11b-a6eebc401a19,Fully Paid,11520,Short Term,741.0,10+ years,Home Mortgage,33694.0,Debt Consolidation,$584.03,12.3,41.0,10,0,6760,16056,0.0,0.0
1,00002c49-3a29-4bd4-8f67-c8f8fbc1048c,927b388d-2e01-423f-a8dc-f7e42d668f46,Fully Paid,3441,Short Term,734.0,4 years,Home Mortgage,42269.0,other,"$1,106.04",26.3,NaN,17,0,6262,19149,0.0,0.0
2,00002d89-27f3-409b-aa76-90834f359a65,defce609-c631-447d-aad6-1270615e89c4,Fully Paid,21029,Short Term,747.0,10+ years,Home Mortgage,90126.0,Debt Consolidation,"$1,321.85",28.8,NaN,5,0,20967,28335,0.0,0.0
3,00005222-b4d8-45a4-ad8c-186057e24233,070bcecb-aae7-4485-a26a-e0403e7bb6c5,Fully Paid,18743,Short Term,747.0,10+ years,Own Home,38072.0,Debt Consolidation,$751.92,26.2,NaN,9,0,22529,43915,0.0,0.0
4,0000757f-a121-41ed-b17b-162e76647c1f,dde79588-12f0-4811-bab0-e2b07f633fcd,Fully Paid,11731,Short Term,746.0,4 years,Rent,50025.0,Debt Consolidation,$355.18,11.5,NaN,12,0,17391,37081,0.0,0.0


In [5]:
df.shape

(256984, 19)

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 256984 entries, 0 to 256983
Data columns (total 19 columns):
 #   Column                        Non-Null Count   Dtype  
---  ------                        --------------   -----  
 0   Loan ID                       256984 non-null  object 
 1   Customer ID                   256984 non-null  object 
 2   Loan Status                   256984 non-null  object 
 3   Current Loan Amount           256984 non-null  int64  
 4   Term                          256984 non-null  object 
 5   Credit Score                  195308 non-null  float64
 6   Years in current job          245508 non-null  object 
 7   Home Ownership                256984 non-null  object 
 8   Annual Income                 195308 non-null  float64
 9   Purpose                       256984 non-null  object 
 10  Monthly Debt                  256984 non-null  object 
 11  Years of Credit History       256984 non-null  float64
 12  Months since last delinquent  116601 non-nul

In [7]:
df.describe()

,Current Loan Amount,Credit Score,Annual Income,Years of Credit History,Months since last delinquent,Number of Open Accounts,Number of Credit Problems,Current Credit Balance,Bankruptcies,Tax Liens
count,2.569840e+05,195308.000000,1.953080e+05,256984.000000,116601.000000,256984.000000,256984.000000,2.569840e+05,256455.000000,256961.000000
mean,1.371331e+07,1251.116099,7.195272e+04,18.290195,34.881450,11.106267,0.156628,1.540656e+04,0.110316,0.027203
std,3.438131e+07,1762.016848,5.887757e+04,7.075747,21.854165,4.982982,0.460731,1.966506e+04,0.336229,0.245950
min,5.050000e+02,585.000000,0.000000e+00,3.400000,0.000000,0.000000,0.000000,0.000000e+00,0.000000,0.000000
25%,8.299000e+03,714.000000,4.432100e+04,13.500000,16.000000,8.000000,0.000000,5.974000e+03,0.000000,0.000000
50%,1.429800e+04,733.000000,6.124200e+04,17.000000,32.000000,10.000000,0.000000,1.107800e+04,0.000000,0.000000
75%,2.436700e+04,744.000000,8.646200e+04,21.700000,51.000000,14.000000,0.000000,1.931900e+04,0.000000,0.000000
max,1.000000e+08,7510.000000,8.713547e+06,70.500000,176.000000,76.000000,11.000000,1.731412e+06,7.000000,11.000000


In [8]:
df = df.drop(df[['Loan ID','Customer ID']], axis = 1)

In [9]:
df.head()

,Loan Status,Current Loan Amount,Term,Credit Score,Years in current job,Home Ownership,Annual Income,Purpose,Monthly Debt,Years of Credit History,Months since last delinquent,Number of Open Accounts,Number of Credit Problems,Current Credit Balance,Maximum Open Credit,Bankruptcies,Tax Liens
0,Fully Paid,11520,Short Term,741.0,10+ years,Home Mortgage,33694.0,Debt Consolidation,$584.03,12.3,41.0,10,0,6760,16056,0.0,0.0
1,Fully Paid,3441,Short Term,734.0,4 years,Home Mortgage,42269.0,other,"$1,106.04",26.3,NaN,17,0,6262,19149,0.0,0.0
2,Fully Paid,21029,Short Term,747.0,10+ years,Home Mortgage,90126.0,Debt Consolidation,"$1,321.85",28.8,NaN,5,0,20967,28335,0.0,0.0
3,Fully Paid,18743,Short Term,747.0,10+ years,Own Home,38072.0,Debt Consolidation,$751.92,26.2,NaN,9,0,22529,43915,0.0,0.0
4,Fully Paid,11731,Short Term,746.0,4 years,Rent,50025.0,Debt Consolidation,$355.18,11.5,NaN,12,0,17391,37081,0.0,0.0


In [10]:
df.shape

(256984, 17)

## Boş verileri işleme

In [11]:
df.isnull().sum()

Loan Status                          0
Current Loan Amount                  0
Term                                 0
Credit Score                     61676
Years in current job             11476
Home Ownership                       0
Annual Income                    61676
Purpose                              0
Monthly Debt                         0
Years of Credit History              0
Months since last delinquent    140383
Number of Open Accounts              0
Number of Credit Problems            0
Current Credit Balance               0
Maximum Open Credit                  0
Bankruptcies                       529
Tax Liens                           23
dtype: int64

In [12]:
def mis_val_cal(df) :
    mis_val = df.isnull().sum() 
    mis_val_percent = 100 * df.isnull().sum() / len(df) # eksik verilerin yüzde kaç olduğunu bulduk
    mis_val_table = pd.concat([mis_val, mis_val_percent], axis=1) # eksik verilerin sayısıyla yüzdesini birleştirdik
    mis_val_table_ren_columns = mis_val_table.rename(
        columns = {0 : 'Missing Values', 1 : '% of Total Values'}) # kolon ismi verdik
    return mis_val_table_ren_columns

In [13]:
mis_val_cal(df)

,Missing Values,% of Total Values
Loan Status,0,0.000000
Current Loan Amount,0,0.000000
Term,0,0.000000
Credit Score,61676,23.999938
Years in current job,11476,4.465648
Home Ownership,0,0.000000
Annual Income,61676,23.999938
Purpose,0,0.000000
Monthly Debt,0,0.000000
Years of Credit History,0,0.000000


In [14]:
df = df.drop(df[['Months since last delinquent']] , axis = 1) # kolonun yüzde 50 den fazlası boş olduğu için kolonu kaldırdık

In [15]:
df.shape

(256984, 16)

In [16]:
df.dropna(subset=["Years in current job"], inplace=True) # Years in current job sütunundaki nan olan satırları sildik

In [17]:
df.shape

(245508, 16)

In [18]:
df.dropna(subset=["Bankruptcies"], inplace=True)

In [19]:
df.dropna(subset=["Tax Liens"], inplace=True)

In [20]:
mis_val_cal(df)

,Missing Values,% of Total Values
Loan Status,0,0.000000
Current Loan Amount,0,0.000000
Term,0,0.000000
Credit Score,58880,24.034713
Years in current job,0,0.000000
Home Ownership,0,0.000000
Annual Income,58880,24.034713
Purpose,0,0.000000
Monthly Debt,0,0.000000
Years of Credit History,0,0.000000


In [21]:
df['Credit Score'] = df['Credit Score'].fillna(df['Credit Score'].mean()) # kredi skoru ortalama ile dolduruldu

In [22]:
df['Annual Income'] = df['Annual Income'].fillna(df['Annual Income'].mean()) # yıllık gelir ortalama ile dolduruldu

In [23]:
mis_val_cal(df)

,Missing Values,% of Total Values
Loan Status,0,0.0
Current Loan Amount,0,0.0
Term,0,0.0
Credit Score,0,0.0
Years in current job,0,0.0
Home Ownership,0,0.0
Annual Income,0,0.0
Purpose,0,0.0
Monthly Debt,0,0.0
Years of Credit History,0,0.0


In [24]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 244979 entries, 0 to 256983
Data columns (total 16 columns):
 #   Column                     Non-Null Count   Dtype  
---  ------                     --------------   -----  
 0   Loan Status                244979 non-null  object 
 1   Current Loan Amount        244979 non-null  int64  
 2   Term                       244979 non-null  object 
 3   Credit Score               244979 non-null  float64
 4   Years in current job       244979 non-null  object 
 5   Home Ownership             244979 non-null  object 
 6   Annual Income              244979 non-null  float64
 7   Purpose                    244979 non-null  object 
 8   Monthly Debt               244979 non-null  object 
 9   Years of Credit History    244979 non-null  float64
 10  Number of Open Accounts    244979 non-null  int64  
 11  Number of Credit Problems  244979 non-null  int64  
 12  Current Credit Balance     244979 non-null  int64  
 13  Maximum Open Credit        244979 

In [25]:
df.corr(numeric_only = True)

,Current Loan Amount,Credit Score,Annual Income,Years of Credit History,Number of Open Accounts,Number of Credit Problems,Current Credit Balance,Bankruptcies,Tax Liens
Current Loan Amount,1.000000,-0.135657,0.022642,0.016018,-0.003923,0.000282,0.002963,0.004073,-0.003614
Credit Score,-0.135657,1.000000,-0.031780,-0.013018,0.009325,-0.000278,-0.002379,-0.003310,0.003494
Annual Income,0.022642,-0.031780,1.000000,0.144213,0.116284,-0.006122,0.240980,-0.033324,0.035439
Years of Credit History,0.016018,-0.013018,0.144213,1.000000,0.136600,0.059139,0.210580,0.057596,0.022752
Number of Open Accounts,-0.003923,0.009325,0.116284,0.136600,1.000000,-0.010543,0.220414,-0.017589,0.004339
Number of Credit Problems,0.000282,-0.000278,-0.006122,0.059139,-0.010543,1.000000,-0.101584,0.755708,0.584786
Current Credit Balance,0.002963,-0.002379,0.240980,0.210580,0.220414,-0.101584,1.000000,-0.114997,-0.011504
Bankruptcies,0.004073,-0.003310,-0.033324,0.057596,-0.017589,0.755708,-0.114997,1.000000,0.047006
Tax Liens,-0.003614,0.003494,0.035439,0.022752,0.004339,0.584786,-0.011504,0.047006,1.000000


In [26]:
df_x = df.drop(df[['Loan Status']], axis = 1)

In [27]:
df_x = pd.get_dummies(df_x, columns=['Term', 'Years in current job', 'Home Ownership', 'Purpose'], drop_first=True)

In [28]:
df_y = df['Loan Status']

In [29]:
df_x.shape

(244979, 34)

In [30]:
df_x.info()

<class 'pandas.core.frame.DataFrame'>
Index: 244979 entries, 0 to 256983
Data columns (total 34 columns):
 #   Column                          Non-Null Count   Dtype  
---  ------                          --------------   -----  
 0   Current Loan Amount             244979 non-null  int64  
 1   Credit Score                    244979 non-null  float64
 2   Annual Income                   244979 non-null  float64
 3   Monthly Debt                    244979 non-null  object 
 4   Years of Credit History         244979 non-null  float64
 5   Number of Open Accounts         244979 non-null  int64  
 6   Number of Credit Problems       244979 non-null  int64  
 7   Current Credit Balance          244979 non-null  int64  
 8   Maximum Open Credit             244979 non-null  object 
 9   Bankruptcies                    244979 non-null  float64
 10  Tax Liens                       244979 non-null  float64
 11  Term_Short Term                 244979 non-null  bool   
 12  Years in current job_

In [31]:
df_x['Annual Income'] = pd.to_numeric(df['Annual Income'].replace('[\$,]', '', regex=True), errors='coerce')

In [32]:
df_x['Monthly Debt'] = pd.to_numeric(df['Monthly Debt'].replace('[\$,]', '', regex=True), errors='coerce')

In [33]:
df_x['Maximum Open Credit'] = pd.to_numeric(df['Maximum Open Credit'], errors='coerce')

In [34]:
nan_count = df_x['Maximum Open Credit'].isna().sum()
print(f'NaN değer sayısı: {nan_count}')

NaN değer sayısı: 4


In [35]:
df_x['Maximum Open Credit'].fillna(0, inplace=True)

C:\Users\USER\AppData\Local\Temp\ipykernel_27992\1635283407.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df_x['Maximum Open Credit'].fillna(0, inplace=True)


In [36]:
df_x.info()

<class 'pandas.core.frame.DataFrame'>
Index: 244979 entries, 0 to 256983
Data columns (total 34 columns):
 #   Column                          Non-Null Count   Dtype  
---  ------                          --------------   -----  
 0   Current Loan Amount             244979 non-null  int64  
 1   Credit Score                    244979 non-null  float64
 2   Annual Income                   244979 non-null  float64
 3   Monthly Debt                    244979 non-null  float64
 4   Years of Credit History         244979 non-null  float64
 5   Number of Open Accounts         244979 non-null  int64  
 6   Number of Credit Problems       244979 non-null  int64  
 7   Current Credit Balance          244979 non-null  int64  
 8   Maximum Open Credit             244979 non-null  float64
 9   Bankruptcies                    244979 non-null  float64
 10  Tax Liens                       244979 non-null  float64
 11  Term_Short Term                 244979 non-null  bool   
 12  Years in current job_

In [37]:
from sklearn.preprocessing import normalize,scale

In [41]:
df_x=normalize(df_x)

In [42]:
df_x

array([[2.90518527e-01, 1.86869990e-02, 8.49716255e-01, ...,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00],
       [7.32597291e-02, 1.56270390e-02, 8.99917317e-01, ...,
        0.00000000e+00, 0.00000000e+00, 2.12902438e-05],
       [2.12319839e-01, 7.54210471e-03, 9.09959477e-01, ...,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00],
       ...,
       [2.08592767e-01, 1.28433645e-01, 9.03924946e-01, ...,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00],
       [2.10317101e-01, 1.29495343e-02, 9.11397250e-01, ...,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00],
       [2.00952837e-01, 4.88301997e-03, 8.46102045e-01, ...,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00]])

In [44]:
negative_count = (df_x < 0).sum().sum()

In [48]:
if (df_x < 0).any().any():
    # Shift values to make them non-negative
    df_x = df_x + abs(df_x.min())

In [49]:
df_x.shape

(244979, 34)

In [50]:
df_y = pd.get_dummies(df_y, drop_first= True )

In [51]:
df_y.head()

,Fully Paid
0,True
1,True
2,True
3,True
4,True


In [52]:
df_y.shape

(244979, 1)

## Veri işlemleri bitti

## Model

In [53]:
#pip install tensorflow

In [54]:
import tensorflow as tf

In [55]:
from tensorflow.keras.models import Sequential

In [56]:
from tensorflow.keras.layers import Dense

In [57]:
from tensorflow.keras.callbacks import EarlyStopping

In [58]:
early_stop = EarlyStopping() # epoch sayısı ne kadar olursa olsun en başarılı epoch sayısını bulunca durur

In [59]:
model = Sequential()
model.add(Dense(34, activation='relu'))
model.add(Dense(68, activation='relu'))
model.add(Dense(128, activation='relu'))
model.add(Dense(64, activation='relu'))
model.add(Dense(32, activation='relu'))
model.add(Dense(1, activation='sigmoid'))

model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])


In [60]:
from sklearn.model_selection import train_test_split

In [61]:
x_train,x_test,y_train,y_test=train_test_split(df_x,df_y,test_size=0.2,random_state=42)

In [62]:
history = model.fit(x_train ,y_train , epochs = 250, batch_size = 32 , validation_split = 0.10 , callbacks=[early_stop], verbose = 1)

Epoch 1/250
5512/5512 ━━━━━━━━━━━━━━━━━━━━ 6s 861us/step - accuracy: 0.7477 - loss: 0.4899 - val_accuracy: 0.7524 - val_loss: 0.4838
Epoch 2/250
5512/5512 ━━━━━━━━━━━━━━━━━━━━ 5s 820us/step - accuracy: 0.7504 - loss: 0.4837 - val_accuracy: 0.7514 - val_loss: 0.4808
Epoch 3/250
5512/5512 ━━━━━━━━━━━━━━━━━━━━ 4s 807us/step - accuracy: 0.7511 - loss: 0.4825 - val_accuracy: 0.7535 - val_loss: 0.4820


In [63]:
tahmin = model.predict(x_test)

1532/1532 ━━━━━━━━━━━━━━━━━━━━ 1s 464us/step 


In [64]:
from sklearn.metrics import r2_score , mean_squared_error

In [65]:
r2=r2_score(y_test , tahmin)

In [66]:
r2

0.22152495384216309

In [67]:
mean_squared_error = mean_squared_error(y_test , tahmin )**.5

In [68]:
 mean_squared_error

0.4082647030758766

In [69]:
from sklearn.linear_model import LogisticRegression
from sklearn.neighbors import KNeighborsClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.ensemble import AdaBoostClassifier
from sklearn.ensemble import GradientBoostingClassifier
from sklearn.naive_bayes import MultinomialNB
from sklearn.naive_bayes import BernoulliNB

from sklearn.metrics import accuracy_score, precision_score, recall_score
from sklearn.metrics import f1_score, confusion_matrix, classification_report
from sklearn.model_selection import train_test_split

b = BernoulliNB()
l = LogisticRegression()
d = DecisionTreeClassifier()
r = RandomForestClassifier()
gb= GradientBoostingClassifier()
kn= KNeighborsClassifier()
ab= AdaBoostClassifier()
mn= MultinomialNB()

def algo_test(x, y):
    modeller=[ b, l, d, r, gb, kn, ab, mn]
    isimler=["BernoulliNB", "LogisticRegression", "DecisionTreeClassifier", 
             "RandomForestClassifier", "GradientBoostingClassifier", "KNeighborsClassifier",
             "AdaBoostClassifier", "MultinomialNB"]

    x_train, x_test, y_train, y_test = train_test_split(df_x, df_y, test_size=.3, random_state = 42)
    
    accuracy = []
    precision = []
    recall = []
    f1 = []
    mdl=[]

    print("Veriler hazır modeller deneniyor")
    for model in modeller:
        print(model, " modeli eğitiliyor!..")
        model=model.fit(x_train,y_train)
        tahmin=model.predict(x_test)
        mdl.append(model)
        accuracy.append(accuracy_score(y_test, tahmin))
        precision.append(precision_score(y_test, tahmin, average="micro"))
        recall.append(recall_score(y_test, tahmin, average="micro"))
        f1.append(f1_score(y_test, tahmin, average="micro"))
        print(confusion_matrix(y_test, tahmin))

    print("Eğitim tamamlandı.")
    
    metrics=pd.DataFrame(columns=["Accuracy", "Precision", "Recall", "F1", "Model"], index=isimler)
    metrics["Accuracy"] = accuracy
    metrics["Precision"] = precision  
    metrics["Recall"] = recall
    metrics["F1"] = f1
    metrics["Model"]=mdl

    metrics.sort_values("F1", ascending=False, inplace=True)

    print("En başarılı model: ", metrics.iloc[0].name)
    model=metrics.iloc[0,-1]
    tahmin=model.predict(np.array(x_test) if model==kn else x_test)
    print("Confusion Matrix:")
    print(confusion_matrix(y_test, tahmin))
    print("classification Report:")
    print(classification_report(y_test, tahmin))
    print("Diğer Modeller:")
    
    return metrics.drop("Model", axis=1)

In [70]:
algo_test(df_x , df_y)

Veriler hazır modeller deneniyor
BernoulliNB()  modeli eğitiliyor!..
[[ 3306 19421]
 [ 2992 47775]]
LogisticRegression()  modeli eğitiliyor!..


C:\Users\USER\anaconda3\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\USER\anaconda3\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


[[ 4769 17958]
 [  512 50255]]
DecisionTreeClassifier()  modeli eğitiliyor!..
[[14870  7857]
 [10467 40300]]
RandomForestClassifier()  modeli eğitiliyor!..


C:\Users\USER\anaconda3\Lib\site-packages\sklearn\base.py:1389: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)


[[12821  9906]
 [ 2642 48125]]
GradientBoostingClassifier()  modeli eğitiliyor!..


C:\Users\USER\anaconda3\Lib\site-packages\sklearn\preprocessing\_label.py:110: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


[[ 7600 15127]
 [ 2423 48344]]
KNeighborsClassifier()  modeli eğitiliyor!..


C:\Users\USER\anaconda3\Lib\site-packages\sklearn\neighbors\_classification.py:239: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return self._fit(X, y)


[[ 9869 12858]
 [ 7579 43188]]
AdaBoostClassifier()  modeli eğitiliyor!..


C:\Users\USER\anaconda3\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


[[ 6882 15845]
 [ 2402 48365]]
MultinomialNB()  modeli eğitiliyor!..
[[    0 22727]
 [    0 50767]]
Eğitim tamamlandı.
En başarılı model:  RandomForestClassifier


C:\Users\USER\anaconda3\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


Confusion Matrix:
[[12821  9906]
 [ 2642 48125]]
classification Report:
              precision    recall  f1-score   support

       False       0.83      0.56      0.67     22727
        True       0.83      0.95      0.88     50767

    accuracy                           0.83     73494
   macro avg       0.83      0.76      0.78     73494
weighted avg       0.83      0.83      0.82     73494

Diğer Modeller:


,Accuracy,Precision,Recall,F1
RandomForestClassifier,0.829265,0.829265,0.829265,0.829265
GradientBoostingClassifier,0.761205,0.761205,0.761205,0.761205
AdaBoostClassifier,0.751721,0.751721,0.751721,0.751721
DecisionTreeClassifier,0.750674,0.750674,0.750674,0.750674
LogisticRegression,0.748687,0.748687,0.748687,0.748687
KNeighborsClassifier,0.721923,0.721923,0.721923,0.721923
BernoulliNB,0.695036,0.695036,0.695036,0.695036
MultinomialNB,0.690764,0.690764,0.690764,0.690764
